### PR TITLE
add support for woot.com

### PR DESCRIPTION
**Pull request by busches**
Sample URL: https://shirt.woot.com/plus/5-shirts-for-30

image

All the images have a `._SX240_` suffix, wasn't sure the best way to replace it, but this worked. Open to suggestions.

### CODE REVIEW

**Comment by extesy** [comment]
@busches Thank you for the contribution. Why limit the plugin to shirts, though? Can it be generalized to work on all woot.com subdomains?

**Comment by busches** [comment]
Probably, but I did a quick test and it didn't work and that's when the laziness kicked in. 😄

**Comment by busches** [comment]
I was able to make a generic regex and it works on woot subdomains, e.g. shirt and computer, but not on woot itself. The markup is a bit different, where you can't actually hover the image there, but instead the bottom div here blocks it. If I remove the div, then the hover works fine. Any recommendations on how to handle this or an example to point me to?

```html
<div class="css-175oi2r r-1kihuf0 r-mnhjs r-1uc7a3i r-ku1wi2 r-38x2cy r-18nae09">
   <div class="css-175oi2r r-1mlwlqe r-1udh08x" style="width: 202.44px; height: 151.83px; z-index: -1; position: absolute; inset: 0px;">
      <div class="css-175oi2r r-1niwhzg r-vvn4in r-u6sd8q r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw r-4gszlv" style="background-image: url(&quot;https://images-na.ssl-images-amazon.com/images/S/mediaservice.woot.com/7f77b82e-11c1-4c48-b587-353d12fce1e9._AC_UX254_SR254,190_.jpg&quot;);"></div>
      <img alt="" draggable="false" src="https://images-na.ssl-images-amazon.com/images/S/mediaservice.woot.com/7f77b82e-11c1-4c48-b587-353d12fce1e9._AC_UX254_SR254,190_.jpg" class="css-9pa8cd hoverZoomLink">
   </div>
	<!-- This is the div that is focused and blocks the render -->
   <div class="css-175oi2r r-3qq6mw r-1pi2tsx r-13qz1uu"></div>
</div>
```

**Comment by busches** [comment]
I was able to get it to work across all the pages on woot I came across.

**Comment by extesy** [comment]
Great work, thank you!

**Pull request merged**
