### PR TITLE
Add middle click and right click as action keys

### PR DESCRIPTION
**Pull request by LiliaDoe**
Fully adds right click and middle click as an action key. Before, right key was showing as an action key but was only being handled for 'lockImage'. This updates it so right click and middle click are completely useable as a key.

### Caveats and Issues I couldn't figure out:
- Middle click still does it's normal function, even after HZ+ function triggers. Right click doesn't
    - event.preventDefault() wasn't working to fix the issue, even after trying many things with it. 
- The hold delay is set to 150ms. It felt short enough to not wait, but it was long enough to not trigger accidentally
- Some buttons that don't require an image to be shown might trigger accidentally with normal use. E.g. toggle HZ+ when it's set to middle mouse click.
- The performance hit shouldn't be noticeable as a switch case is used to handle mouse events, but it is still triggered with every right and middle mouse click, even when they aren't selected for any action key.

### CODE REVIEW

**Comment by LiliaDoe** [comment]
Do you want me to move some of the duplicate functions in popup.js and options.js to common.js? Like keyCodeToString(), initActionKeys(), and loadKeys(sel)?

**Comment by extesy** [comment]
@LiliaDoe Yeah, that would be nice. Also I'm not sure this is a good idea:

> Due to the reworking of the special codes for mouse buttons, action keys previously set to 'none' or 'right click' won't work or will show blank.

I've always tried to preserve backwards compatibility as much as possible. Whatever new functionality is added, nothing should change for existing users. Forcing them to re-select their already selected action keys doesn't seem user friendly.

**Comment by LiliaDoe** [comment]
Gotcha. I can use an array to select which mouse button was pressed instead.

**Comment by LiliaDoe** [comment]
That should be backwards compatible now

**Pull request merged**
