### PR TITLE
Zoom Reddit single and gallery images

### PR DESCRIPTION
**Pull request by weimeng**
Adds handling for single and gallery images on reddit.com.

### CODE REVIEW

**Comment by extesy** [comment]
@weimeng Hoverzoom can already zoom gallery images on reddit. Closing as invalid bug report.

**Comment by extesy** [comment]
@weimeng Can you please provide urls where this new functionality can be tested? I have not personally encountered any cases where galleries didn't already work.

**Comment by weimeng** [comment]
Sure!

https://www.reddit.com/user/chloekoala333/ (specifically the post titled "Lil klepto doodle") would be representative of when a gallery is in the feed view.

And if you click into the [actual post](https://www.reddit.com/r/AceAttorney/comments/10w61op/lil_klepto_doodle/), the current behaviour is that a gallery's single image gets zoomed. I've adjusted this so that the entire gallery is zoomed and you can navigate all images.

**Comment by weimeng** [comment]
I can take a video to show the current behaviour if you need it, but I'll only be able to do so in about 8 to 10 hours.

**Comment by extesy** [comment]
This is weird. I am able to zoom all the images that you mentioned, including a gallery on a "Lil klepto doodle" post.

Can you please try the latest master branch instead of the latest webstore version? There are two recent commits (98841bc49d35e16eba9ddf60caa13d815076056f and 74521eaa47e74dc02589967f3cbc3a469077082f) which improved reddit plugin. Make sure you've tried those first.

**Comment by weimeng** [comment]
That's pretty strange! I just tried with master at the latest commit (8a33f138ec260e07d69d6794f628de729c2968b0) and I'm not able to zoom any of the images on the page I linked.

Here's a screen recording of what I'm seeing:
https://user-images.githubusercontent.com/1473065/217574861-70a90030-86cf-4709-b2ae-af0db2ce6201.mp4

I'm using Microsoft Edge, and I disabled all other extensions except Hoverzoom, just in case something was interfering.

**Comment by extesy** [comment]
Thanks for the video! I see that you are using "new" reddit and I've set "old" reddit as a default one, that's why I couldn't reproduce. Let me look into this.

**Pull request merged**
