### PR TITLE
Firefox support

### PR DESCRIPTION
**Pull request by Mte90**
With this fix the extension works without problems on Firefox

### CODE REVIEW

**Comment by extesy** [comment]
@Mte90 why change the extension package name?

**Comment by Mte90** [comment]
If you do now `npm install` you get an error for a wrong name that contain symbols :-)

**Comment by extesy** [comment]
Why do you need to run `npm install`? Changing package name might have unintended consequences for Chrome Webstore and I would prefer to avoid that risk.

**Comment by Mte90** [comment]
I changed the name on package.json that is used by `npm` the chrome webstore use manifest.json :-)

**Comment by extesy** [comment]
I see, my bad. Looks good to me!

**Pull request merged**
