### PR TITLE
Fix: images showing when mouse is off image link

### PR DESCRIPTION
**Pull request by LiliaDoe**
- This might fix the issue described in https://github.com/extesy/hoverzoom/pull/1489#issuecomment-2564391188

### CODE REVIEW

**Comment by extesy** [comment]
This PR fixed the problem, so I'm merging it.

**Comment by LiliaDoe** [comment]
Glad to hear!

**Comment by extesy** [comment]
@LiliaDoe I spoke too soon, I'm still seeing this problem. Repro steps (can repro on reddit as well but this one is easier):
1. Open https://forums.crateentertainment.com/t/announcing-fangs-of-asterkarn/129879
2. Set "delay before displaying a picture" to some reasonably high value.
3. Briefly move the cursor into the picture and immediately move it far away.

Observed: the zoomed mage is still displayed even though the mouse is no longer hovering over it.
Desired: only display the image if the mouse is hovering over it.

**Comment by LiliaDoe** [comment]
Ok, I can reproduce it consistently now. For the sake of the bug, it seems like a flag or variable is set to true once an image is zoomed the first time and not changing to false once the image stops being zoomed. My tests show (for me):
- Clicking on the page resets the "flag"
- Once an image on the page is zoomed, the "flag" is turned on for whatever triggers the bug
- When the "flag" is on, hovering around half the delay time and moving the mouse off the image will cause it to zoom

**Comment by LiliaDoe** [comment]
I believe I found the source of the issue:
https://github.com/extesy/hoverzoom/blob/4cb6b61a03bdbee5a86eb8622db98368cf64b399/js/hoverzoom.js#L1074-L1086

changing it back to how it was prior made it behave as expected for me:
https://github.com/extesy/hoverzoom/blob/6b9717edd0d8b5da453381bbe60470bd2ca3b2ea/js/hoverzoom.js#L1071-L1074

While it's not my code, I will work on a solution

**Comment by extesy** [comment]
Thank you for finding the problem. I thought I bi-sected the problem to your commit, but I guess I made a mistake while doing that. Please accept my apologies!

**Pull request merged**
