### PR TITLE
Fix: sh.reddit.com search and compact view not loading

### PR DESCRIPTION
**Pull request by LiliaDoe**
Made sh.reddit search and compact view media load.
- In searches, selecting only the thumbnails allowed it to load, while in normal compact view, selecting the whole faceplate allowed it to load. Not sure why. I want to streamline it, but for now, things work as expected.
- Might allow searches to load media in old.reddit as well in the future

### CODE REVIEW

**Comment by LiliaDoe** [comment]
I'll work on reducing the duplicatiton later

**Comment by extesy** [comment]
When you are going to test this, please make sure that old.reddit.com still works fine. Old reddit is the best reddit.

**Comment by LiliaDoe** [comment]
Do I need to reduce the duplication? I can work on it, but I see that was there from previous commits. I'm a little afraid to change any of it in case some part of old.reddit with a gallery stops working, to be honest.

**Comment by LiliaDoe** [comment]
I've tried reducing the duplicate lines, and i think I got it as low as I can without changing previous code too much. There were more errors with my changes than I expected, but after looking over it for a while, everything is working. The places I tested on old.reddit.com and sh.reddit.com are: galleries, images, and videos, in subreddits and home feed. The only thing not working is searches on old.reddit.com, something that wasn't working previously.

**Comment by LiliaDoe** [comment]
I looked over the whole file again, and made sure the old code was how it was when I found it, with updated variable scopes. My only concern is new reddit tends to run slower than old reddit, but I think that's just the nature of the websites rather than HZ+

**Comment by extesy** [comment]
Seems to work for me. Thank you!

**Comment by LiliaDoe** [comment]
Also, this fixes #1390 and possibly #458

**Comment by LiliaDoe** [comment]
If users report issues with sh.reddit.com searches not loading when mouse hasn't moved, one could resolve it by changing:
```js
    $('faceplate-tracker[data-faceplate-tracking-context*="post_thumbnail"]').each(function () {
```
to
```js
    $('faceplate-tracker[data-faceplate-tracking-context*="post_thumbnail"]').one('mouseover', function () {
```
Using .each() just makes images load faster

**Pull request merged**
