### PR TITLE
added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by 0Armaan025**

### CODE REVIEW

**Comment by GrosPoulet** [comment]
Good idea @0Armaan025, some day i should add a guide on how-to write plug-ins :smirk:
BTW there is no HZ+ community (yet) : https://app.gitter.im/#/room/#hoverzoom_community:gitter.im

**Comment by 0Armaan025** [comment]
should I add the links? 👀

**Comment by GrosPoulet** [comment]
idk, i do not use Gitter, @extesy what's your opinion ?

**Comment by extesy** [comment]
I don't use gitter either, and won't have time to hang out in any other chats like discord. I don't think we should advertise a community that we personally don't use.

**Comment by 0Armaan025** [comment]
Apologises for the trouble, just fixed it! ⭐

**Comment by extesy** [comment]
Thank you, @0Armaan025!

**Pull request merged**
