### PR TITLE
Home Exchange Plugin

### PR DESCRIPTION
**Pull request by hytea**
I have created a plugin for the homeexchange.com website.

Thanks for the awesome extension and plugin system! Can't wait for the developer docs for plugins I saw you just created the issue for that recently.

image

### CODE REVIEW

**Comment by hytea** [comment]
Hmm... I copied the format of other recently merged plugins and the "issues" the DeepSource JS check is complaining about are all things in almost all of the other plugins.

**Comment by extesy** [comment]
Thank you for the contribution!

**Comment by hytea** [comment]
@extesy 
No problem! I love the extension. 

FYI: Hacktoberfest is going on now. I would love to contribute more and get credit for Hacktoberfest for those contributions. 
To enable that you or another maintainer can [add the “hacktoberfest” topic to your repository to OPT-IN TO HACKTOBERFEST](https://hacktoberfest.com/participation/#maintainers).

Could be a fun way for you to attract more contributions too.

**Comment by GrosPoulet** [comment]
@extesy i think we can add this "hacktoberfest" topic, in case it generates too much spam/invalid PR we can just remove it.

**Comment by extesy** [comment]
@GrosPoulet Already done:
image

**Comment by hytea** [comment]
He added it already. Thanks!

**Pull request merged**
