### PR TITLE
Added plugin for: artlimited.net

### PR DESCRIPTION
**Pull request by GrosPoulet**
New plugin: artlimited.js

### CODE REVIEW

**Comment by extesy** [comment]
@GrosPoulet Could you please rebase your PR so that I could automatically merge it?

**Comment by GrosPoulet** [comment]
I solved the conflict on manifest.json, it should be OK now.

**Comment by extesy** [comment]
Thanks!

**Comment by GrosPoulet** [comment]
Thanks to you!

Some more new plugins coming soon :-)

**Pull request merged**
